sudo: required
language: go
services:
  - docker
before_install:
  - export GO111MODULE=on
  - docker run -p 6379:6379 -d redis
  - go mod vendor
  - curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protoc-3.7.0-linux-x86_64.zip
  - unzip protoc-3.7.0-linux-x86_64.zip -d protoc3
  - sudo mv protoc3/bin/* /usr/local/bin/
  - sudo mv protoc3/include/* /usr/local/include/
  - rm -f proto3
  - go get -u google.golang.org/grpc
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go install github.com/golang/protobuf/protoc-gen-go
  - go generate -x ./...
script:
  - go test ./...
