// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package job

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Id struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}
func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (dst *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(dst, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type IdList struct {
	Ids                  []*Id    `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdList) Reset()         { *m = IdList{} }
func (m *IdList) String() string { return proto.CompactTextString(m) }
func (*IdList) ProtoMessage()    {}
func (*IdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}
func (m *IdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdList.Unmarshal(m, b)
}
func (m *IdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdList.Marshal(b, m, deterministic)
}
func (dst *IdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdList.Merge(dst, src)
}
func (m *IdList) XXX_Size() int {
	return xxx_messageInfo_IdList.Size(m)
}
func (m *IdList) XXX_DiscardUnknown() {
	xxx_messageInfo_IdList.DiscardUnknown(m)
}

var xxx_messageInfo_IdList proto.InternalMessageInfo

func (m *IdList) GetIds() []*Id {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Job struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Unique               bool     `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	When                 int64    `protobuf:"varint,4,opt,name=when,proto3" json:"when,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{2}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Job) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func (m *Job) GetWhen() int64 {
	if m != nil {
		return m.When
	}
	return 0
}

type JobList struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobList) Reset()         { *m = JobList{} }
func (m *JobList) String() string { return proto.CompactTextString(m) }
func (*JobList) ProtoMessage()    {}
func (*JobList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{3}
}
func (m *JobList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobList.Unmarshal(m, b)
}
func (m *JobList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobList.Marshal(b, m, deterministic)
}
func (dst *JobList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobList.Merge(dst, src)
}
func (m *JobList) XXX_Size() int {
	return xxx_messageInfo_JobList.Size(m)
}
func (m *JobList) XXX_DiscardUnknown() {
	xxx_messageInfo_JobList.DiscardUnknown(m)
}

var xxx_messageInfo_JobList proto.InternalMessageInfo

func (m *JobList) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{4}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Id)(nil), "Id")
	proto.RegisterType((*IdList)(nil), "IdList")
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterType((*JobList)(nil), "JobList")
	proto.RegisterType((*Void)(nil), "Void")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobsClient is the client API for Jobs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobsClient interface {
	Push(ctx context.Context, in *JobList, opts ...grpc.CallOption) (*IdList, error)
	Remove(ctx context.Context, in *IdList, opts ...grpc.CallOption) (*Void, error)
}

type jobsClient struct {
	cc *grpc.ClientConn
}

func NewJobsClient(cc *grpc.ClientConn) JobsClient {
	return &jobsClient{cc}
}

func (c *jobsClient) Push(ctx context.Context, in *JobList, opts ...grpc.CallOption) (*IdList, error) {
	out := new(IdList)
	err := c.cc.Invoke(ctx, "/Jobs/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsClient) Remove(ctx context.Context, in *IdList, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/Jobs/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobsServer is the server API for Jobs service.
type JobsServer interface {
	Push(context.Context, *JobList) (*IdList, error)
	Remove(context.Context, *IdList) (*Void, error)
}

func RegisterJobsServer(s *grpc.Server, srv JobsServer) {
	s.RegisterService(&_Jobs_serviceDesc, srv)
}

func _Jobs_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Jobs/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServer).Push(ctx, req.(*JobList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Jobs_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Jobs/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServer).Remove(ctx, req.(*IdList))
	}
	return interceptor(ctx, in, info, handler)
}

var _Jobs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Jobs",
	HandlerType: (*JobsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Jobs_Push_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Jobs_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0x87, 0x49, 0x13, 0xd3, 0xbb, 0x27, 0x38, 0x3c, 0x54, 0x9e, 0xb7, 0x58, 0xe2, 0xd2, 0x29,
	0xc3, 0x39, 0xfa, 0x17, 0xb4, 0x38, 0x48, 0x06, 0x17, 0xb7, 0x98, 0xc0, 0xe5, 0xc0, 0x3e, 0x35,
	0xa9, 0xfe, 0xfb, 0xd2, 0xd0, 0x2e, 0x6e, 0xf9, 0x3e, 0xf8, 0xf8, 0x91, 0x07, 0xfb, 0x33, 0x7b,
	0xfb, 0xf9, 0xcd, 0x85, 0xcd, 0x35, 0x34, 0x43, 0xc0, 0x2b, 0x68, 0x52, 0x20, 0xd1, 0x89, 0x7e,
	0xef, 0x9a, 0x14, 0xcc, 0x3d, 0xe8, 0x21, 0x3c, 0xa7, 0x5c, 0xf0, 0x06, 0x64, 0x0a, 0x99, 0x44,
	0x27, 0xfb, 0xcb, 0xa3, 0xb4, 0x43, 0x70, 0x0b, 0x9b, 0x37, 0x90, 0x23, 0xfb, 0xff, 0x1d, 0x12,
	0xb4, 0xef, 0x3c, 0x95, 0x38, 0x15, 0x6a, 0xaa, 0xdc, 0x10, 0x6f, 0x41, 0xcf, 0x53, 0xfa, 0x9a,
	0x23, 0xc9, 0x4e, 0xf4, 0x3b, 0xb7, 0x12, 0x22, 0xa8, 0xdf, 0x53, 0x9c, 0x48, 0x75, 0xa2, 0x97,
	0xae, 0xbe, 0xcd, 0x03, 0xb4, 0x23, 0xfb, 0x3a, 0x4f, 0xa0, 0xce, 0xec, 0xb7, 0x7d, 0x65, 0x47,
	0xf6, 0xae, 0x1a, 0xa3, 0x41, 0xbd, 0x72, 0x0a, 0xc7, 0x27, 0x50, 0x23, 0xfb, 0x8c, 0x77, 0xa0,
	0x5e, 0xe6, 0x7c, 0xc2, 0x9d, 0x5d, 0xdb, 0x43, 0x6b, 0xd7, 0x3f, 0x10, 0x68, 0x17, 0x3f, 0xf8,
	0x27, 0xe2, 0xa6, 0x0e, 0x17, 0x76, 0x89, 0xbd, 0xae, 0x47, 0x78, 0xfc, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x71, 0x49, 0x79, 0x00, 0x11, 0x01, 0x00, 0x00,
}
